# Generated by Ansible provisioning/environment_hosts
NORMAL="\[\e[0m\]"
RED="\[\e[31m\]"
GREEN="\[\e[32m\]"
BLUE="\[\e[1;36m\]"
YELLOW="\[\e[33m\]"

if [ "$USER" = "root" ]; then
    PS1="[$RED\u$NORMAL@$YELLOW\H$NORMAL:$BLUE\w$NORMAL]$NORMAL # "
else
    PS1="[$GREEN\u$NORMAL@$YELLOW\H$NORMAL:$BLUE\w$NORMAL]$NORMAL $ "
fi

alias vi="vim"
alias ll='ls -lah'
